In the assertion part of the testing method, we can send the message when the test case has failed.

For that, we need to add an argument to an assertion method. This argument should be always the last argument of the assertion method.

We can send it both as string and lambda expression.

As string:

assertEquals(4, result, "Expected sum to be 4");

As lambda expression:

assertEquals(4, result, () -> "Expected sum to be 4");

-------------------------------------------

Both are similar, but the lambda expression is a little bit beneficial if the message is complex, like that:

assertEquals(4, result, () -> "Expected result to be 4 but got " + result);

Here when the test case has failed, we want to print actual result too.

